/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Timestamp,
  'published' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const Faq = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'answer' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'gradeRange' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'studentName' : IDL.Text,
  'role' : IDL.Text,
  'photoUrl' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AboutContent = IDL.Record({
  'qualifications' : IDL.Text,
  'experience' : IDL.Text,
  'achievements' : IDL.Text,
  'introduction' : IDL.Text,
  'teachingPhilosophy' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'grade' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalServices' : IDL.Nat,
  'totalBlogPosts' : IDL.Nat,
  'totalFAQs' : IDL.Nat,
  'totalSubjects' : IDL.Nat,
  'totalContactMessages' : IDL.Nat,
  'totalTestimonials' : IDL.Nat,
});
export const HeroContent = IDL.Record({
  'subheading' : IDL.Text,
  'ctaButtonLink' : IDL.Text,
  'ctaButtonText' : IDL.Text,
  'headline' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func([BlogPost], [], []),
  'addFAQ' : IDL.Func([Faq], [], []),
  'addService' : IDL.Func([Service], [], []),
  'addSubject' : IDL.Func([Subject], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteContactMessage' : IDL.Func([IDL.Text], [], []),
  'deleteFAQ' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'deleteSubject' : IDL.Func([IDL.Text], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
  'getAboutContent' : IDL.Func([], [IDL.Opt(AboutContent)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(Faq)], ['query']),
  'getAllPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getHeroContent' : IDL.Func([], [IDL.Opt(HeroContent)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'updateAboutContent' : IDL.Func([AboutContent], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateFAQ' : IDL.Func([Faq], [], []),
  'updateHeroContent' : IDL.Func([HeroContent], [], []),
  'updateService' : IDL.Func([Service], [], []),
  'updateSubject' : IDL.Func([Subject], [], []),
  'updateTestimonial' : IDL.Func([Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Timestamp,
    'published' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const Faq = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'gradeRange' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'studentName' : IDL.Text,
    'role' : IDL.Text,
    'photoUrl' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AboutContent = IDL.Record({
    'qualifications' : IDL.Text,
    'experience' : IDL.Text,
    'achievements' : IDL.Text,
    'introduction' : IDL.Text,
    'teachingPhilosophy' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'grade' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalServices' : IDL.Nat,
    'totalBlogPosts' : IDL.Nat,
    'totalFAQs' : IDL.Nat,
    'totalSubjects' : IDL.Nat,
    'totalContactMessages' : IDL.Nat,
    'totalTestimonials' : IDL.Nat,
  });
  const HeroContent = IDL.Record({
    'subheading' : IDL.Text,
    'ctaButtonLink' : IDL.Text,
    'ctaButtonText' : IDL.Text,
    'headline' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func([BlogPost], [], []),
    'addFAQ' : IDL.Func([Faq], [], []),
    'addService' : IDL.Func([Service], [], []),
    'addSubject' : IDL.Func([Subject], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteContactMessage' : IDL.Func([IDL.Text], [], []),
    'deleteFAQ' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'deleteSubject' : IDL.Func([IDL.Text], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
    'getAboutContent' : IDL.Func([], [IDL.Opt(AboutContent)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(Faq)], ['query']),
    'getAllPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getHeroContent' : IDL.Func([], [IDL.Opt(HeroContent)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'updateAboutContent' : IDL.Func([AboutContent], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateFAQ' : IDL.Func([Faq], [], []),
    'updateHeroContent' : IDL.Func([HeroContent], [], []),
    'updateService' : IDL.Func([Service], [], []),
    'updateSubject' : IDL.Func([Subject], [], []),
    'updateTestimonial' : IDL.Func([Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };