/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'qualifications' : string,
  'experience' : string,
  'achievements' : string,
  'introduction' : string,
  'teachingPhilosophy' : string,
}
export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'publishDate' : Timestamp,
  'published' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'imageUrl' : string,
  'excerpt' : string,
}
export interface ContactMessage {
  'id' : string,
  'subject' : string,
  'name' : string,
  'grade' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export interface DashboardStats {
  'totalServices' : bigint,
  'totalBlogPosts' : bigint,
  'totalFAQs' : bigint,
  'totalSubjects' : bigint,
  'totalContactMessages' : bigint,
  'totalTestimonials' : bigint,
}
export interface Faq {
  'id' : string,
  'question' : string,
  'order' : bigint,
  'answer' : string,
}
export interface HeroContent {
  'subheading' : string,
  'ctaButtonLink' : string,
  'ctaButtonText' : string,
  'headline' : string,
}
export interface Service {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'imageUrl' : string,
}
export interface Subject {
  'id' : string,
  'gradeRange' : string,
  'name' : string,
  'description' : string,
  'iconName' : string,
}
export interface Testimonial {
  'id' : string,
  'studentName' : string,
  'role' : string,
  'photoUrl' : string,
  'reviewText' : string,
  'rating' : bigint,
}
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  'addFAQ' : ActorMethod<[Faq], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'addSubject' : ActorMethod<[Subject], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteContactMessage' : ActorMethod<[string], undefined>,
  'deleteFAQ' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'getAboutContent' : ActorMethod<[], [] | [AboutContent]>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllFAQs' : ActorMethod<[], Array<Faq>>,
  'getAllPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getHeroContent' : ActorMethod<[], [] | [HeroContent]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'updateAboutContent' : ActorMethod<[AboutContent], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updateFAQ' : ActorMethod<[Faq], undefined>,
  'updateHeroContent' : ActorMethod<[HeroContent], undefined>,
  'updateService' : ActorMethod<[Service], undefined>,
  'updateSubject' : ActorMethod<[Subject], undefined>,
  'updateTestimonial' : ActorMethod<[Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];